# Generated by Django 3.1.2 on 2020-10-28 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64, verbose_name='Наименование товара')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма сделки')),
                ('quantity', models.IntegerField(verbose_name='Колличество товара, шт')),
                ('date', models.DateTimeField(verbose_name='Дата и время регистрации сделки')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
